//! Brush tip images and grain textures.
//!
//! A [`TipImage`] is a grayscale alpha mask (`0..=1` per texel). Used as a
//! *tip* it replaces the analytic round dab; used as a *texture* it is tiled
//! across the canvas and modulates every dab (paper grain). Both come either
//! from the procedural built-ins here or from user PNGs.

use std::sync::Arc;

/// Deterministic xorshift64* generator (no external crate; reproducible tests).
#[derive(Clone, Debug)]
pub struct Rng(u64);

impl Rng {
    pub fn new(seed: u64) -> Self {
        Self(seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) | 1)
    }

    pub fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    /// Uniform in `0..1`.
    pub fn unit(&mut self) -> f32 {
        (self.next_u64() >> 40) as f32 / (1u64 << 24) as f32
    }

    /// Uniform in `-1..1`.
    pub fn signed(&mut self) -> f32 {
        self.unit() * 2.0 - 1.0
    }
}

#[derive(Clone, Debug)]
pub struct TipImage {
    pub name: String,
    pub width: u32,
    pub height: u32,
    /// Row-major alpha, `0..=1`.
    pub alpha: Arc<[f32]>,
    /// True for images generated by [`builtin_tips`] / [`builtin_textures`].
    pub builtin: bool,
}

impl TipImage {
    pub fn from_alpha(name: impl Into<String>, width: u32, height: u32, alpha: Vec<f32>) -> Self {
        assert_eq!(alpha.len(), (width * height) as usize);
        Self { name: name.into(), width, height, alpha: alpha.into(), builtin: false }
    }

    /// Build a tip from straight-alpha RGBA8 pixels: darker and more opaque
    /// pixels give a stronger tip (Photoshop "Define Brush Preset" semantics).
    pub fn from_rgba_dark(name: impl Into<String>, width: u32, height: u32, rgba: &[u8]) -> Self {
        let alpha = rgba
            .chunks_exact(4)
            .map(|p| {
                let l = (0.2126 * p[0] as f32 + 0.7152 * p[1] as f32 + 0.0722 * p[2] as f32) / 255.0;
                (1.0 - l) * p[3] as f32 / 255.0
            })
            .collect();
        Self::from_alpha(name, width, height, alpha)
    }

    /// Build a grain texture from RGBA8 pixels by luminance (light = full paint).
    pub fn from_rgba_luma(name: impl Into<String>, width: u32, height: u32, rgba: &[u8]) -> Self {
        let alpha = rgba
            .chunks_exact(4)
            .map(|p| {
                let l = (0.2126 * p[0] as f32 + 0.7152 * p[1] as f32 + 0.0722 * p[2] as f32) / 255.0;
                let a = p[3] as f32 / 255.0;
                l * a + (1.0 - a)
            })
            .collect();
        Self::from_alpha(name, width, height, alpha)
    }

    /// Straight-alpha RGBA8 (white with the mask as alpha), for thumbnails and export.
    pub fn to_rgba(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(self.alpha.len() * 4);
        for &a in self.alpha.iter() {
            out.extend_from_slice(&[255, 255, 255, (a.clamp(0.0, 1.0) * 255.0 + 0.5) as u8]);
        }
        out
    }

    #[inline]
    pub fn texel(&self, x: i32, y: i32) -> f32 {
        let x = x.rem_euclid(self.width as i32) as usize;
        let y = y.rem_euclid(self.height as i32) as usize;
        self.alpha[y * self.width as usize + x]
    }

    /// Bilinear sample with wrapping (for tiled textures). `u`,`v` in texels.
    #[inline]
    pub fn sample_wrap(&self, u: f32, v: f32) -> f32 {
        let x0 = u.floor();
        let y0 = v.floor();
        let fx = u - x0;
        let fy = v - y0;
        let (xi, yi) = (x0 as i32, y0 as i32);
        let a = self.texel(xi, yi);
        let b = self.texel(xi + 1, yi);
        let c = self.texel(xi, yi + 1);
        let d = self.texel(xi + 1, yi + 1);
        let top = a + (b - a) * fx;
        let bot = c + (d - c) * fx;
        top + (bot - top) * fy
    }

    /// Bilinear sample in normalized tip space `-1..1` (outside = 0).
    #[inline]
    pub fn sample_tip(&self, nx: f32, ny: f32) -> f32 {
        if nx <= -1.0 || nx >= 1.0 || ny <= -1.0 || ny >= 1.0 {
            return 0.0;
        }
        let u = (nx * 0.5 + 0.5) * self.width as f32 - 0.5;
        let v = (ny * 0.5 + 0.5) * self.height as f32 - 0.5;
        let x0 = u.floor();
        let y0 = v.floor();
        let fx = u - x0;
        let fy = v - y0;
        let get = |x: i32, y: i32| -> f32 {
            if x < 0 || y < 0 || x >= self.width as i32 || y >= self.height as i32 {
                0.0
            } else {
                self.alpha[y as usize * self.width as usize + x as usize]
            }
        };
        let (xi, yi) = (x0 as i32, y0 as i32);
        let a = get(xi, yi);
        let b = get(xi + 1, yi);
        let c = get(xi, yi + 1);
        let d = get(xi + 1, yi + 1);
        let top = a + (b - a) * fx;
        let bot = c + (d - c) * fx;
        top + (bot - top) * fy
    }

    /// Nearest-neighbour resample to `w × h`.
    pub fn resized(&self, w: u32, h: u32) -> TipImage {
        let mut alpha = Vec::with_capacity((w * h) as usize);
        for y in 0..h {
            for x in 0..w {
                let u = (x as f32 + 0.5) / w as f32 * self.width as f32 - 0.5;
                let v = (y as f32 + 0.5) / h as f32 * self.height as f32 - 0.5;
                alpha.push(self.sample_wrap(u, v));
            }
        }
        TipImage { name: self.name.clone(), width: w, height: h, alpha: alpha.into(), builtin: self.builtin }
    }
}

const TIP_PX: u32 = 96;
const TEX_PX: u32 = 128;

fn make(name: &str, w: u32, h: u32, f: impl Fn(f32, f32, &mut Rng) -> f32, seed: u64) -> TipImage {
    let mut rng = Rng::new(seed);
    let mut alpha = Vec::with_capacity((w * h) as usize);
    for y in 0..h {
        for x in 0..w {
            let nx = (x as f32 + 0.5) / w as f32 * 2.0 - 1.0;
            let ny = (y as f32 + 0.5) / h as f32 * 2.0 - 1.0;
            alpha.push(f(nx, ny, &mut rng).clamp(0.0, 1.0));
        }
    }
    let mut t = TipImage::from_alpha(name, w, h, alpha);
    t.builtin = true;
    t
}

/// Value noise on a wrapping lattice of `cells` per axis; returns `0..1`.
fn value_noise(px: f32, py: f32, cells: u32, seed: u64) -> f32 {
    let hash = |x: i32, y: i32| -> f32 {
        let x = x.rem_euclid(cells as i32) as u64;
        let y = y.rem_euclid(cells as i32) as u64;
        let mut r = Rng::new(seed ^ (x * 0x1F1F_1F1F) ^ (y << 20));
        r.unit()
    };
    let x0 = px.floor();
    let y0 = py.floor();
    let fx = px - x0;
    let fy = py - y0;
    let sx = fx * fx * (3.0 - 2.0 * fx);
    let sy = fy * fy * (3.0 - 2.0 * fy);
    let (xi, yi) = (x0 as i32, y0 as i32);
    let a = hash(xi, yi);
    let b = hash(xi + 1, yi);
    let c = hash(xi, yi + 1);
    let d = hash(xi + 1, yi + 1);
    let top = a + (b - a) * sx;
    let bot = c + (d - c) * sx;
    top + (bot - top) * sy
}

/// Fractal (3 octave) wrapping noise in `0..1` for a `u,v` in `0..1`.
fn fbm(u: f32, v: f32, base_cells: u32, seed: u64) -> f32 {
    let mut sum = 0.0;
    let mut amp = 0.5;
    let mut cells = base_cells;
    let mut total = 0.0;
    for o in 0..3 {
        sum += amp * value_noise(u * cells as f32, v * cells as f32, cells, seed + o);
        total += amp;
        amp *= 0.5;
        cells *= 2;
    }
    sum / total
}

/// Procedural tip shapes shipped with the app.
pub fn builtin_tips() -> Vec<TipImage> {
    let disc = |nx: f32, ny: f32| 1.0 - (nx * nx + ny * ny).sqrt();
    let mut v = Vec::new();
    v.push(make(
        "Chalk",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let d = disc(x, y);
            let n = fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 12, 11);
            let n2 = fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 40, 12);
            ((d * 3.0).clamp(0.0, 1.0)) * ((n * 0.7 + n2 * 0.6) - 0.35) * 2.2
        },
        1,
    ));
    v.push(make(
        "Charcoal",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let d = disc(x * 1.1, y * 0.8);
            let n = fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 24, 21);
            (d * 2.0).clamp(0.0, 1.0) * ((n - 0.3) * 2.5).clamp(0.0, 1.0)
        },
        2,
    ));
    v.push(make(
        "Spatter",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let mut a: f32 = 0.0;
            let mut r = Rng::new(31);
            for _ in 0..70 {
                let cx = r.signed() * 0.85;
                let cy = r.signed() * 0.85;
                let rad = 0.03 + r.unit() * 0.10;
                let d = ((x - cx).powi(2) + (y - cy).powi(2)).sqrt();
                a = a.max(((rad - d) / 0.02).clamp(0.0, 1.0));
            }
            a * (disc(x, y) * 4.0).clamp(0.0, 1.0)
        },
        3,
    ));
    v.push(make(
        "Splotch",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let n = fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 4, 41);
            let d = disc(x, y) + (n - 0.5) * 0.7;
            (d * 4.0).clamp(0.0, 1.0)
        },
        4,
    ));
    v.push(make(
        "Scratchy",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let mut a: f32 = 0.0;
            let mut r = Rng::new(51);
            for _ in 0..26 {
                let oy = r.signed() * 0.9;
                let th = 0.006 + r.unit() * 0.02;
                let len = 0.5 + r.unit() * 0.5;
                let d = (y - oy).abs();
                if x.abs() < len {
                    a = a.max(((th - d) / 0.01).clamp(0.0, 1.0) * (0.5 + r.unit() * 0.5));
                }
            }
            a * (disc(x, y) * 3.0).clamp(0.0, 1.0)
        },
        5,
    ));
    v.push(make(
        "Bristle",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let mut a: f32 = 0.0;
            let mut r = Rng::new(61);
            for _ in 0..40 {
                let cx = r.signed() * 0.8;
                let cy = r.signed() * 0.8;
                let rad = 0.04 + r.unit() * 0.05;
                let d = ((x - cx).powi(2) + (y - cy).powi(2)).sqrt();
                a = a.max(((rad - d) / rad).clamp(0.0, 1.0) * (0.6 + r.unit() * 0.4));
            }
            a * (disc(x, y) * 2.5).clamp(0.0, 1.0)
        },
        6,
    ));
    v.push(make(
        "Square",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let m = x.abs().max(y.abs());
            ((0.9 - m) / 0.02).clamp(0.0, 1.0)
        },
        7,
    ));
    v.push(make(
        "Star",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let ang = y.atan2(x);
            let r = (x * x + y * y).sqrt();
            let k = ((ang * 2.5).cos() * 0.5 + 0.5).powf(0.6);
            let edge = 0.35 + 0.55 * k;
            ((edge - r) / 0.03).clamp(0.0, 1.0)
        },
        8,
    ));
    v.push(make(
        "Leaf",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let w = (1.0 - x * x).max(0.0).sqrt() * 0.55;
            let d = w - y.abs();
            let vein = if y.abs() < 0.02 && x > -0.9 { 0.6 } else { 1.0 };
            ((d) / 0.03).clamp(0.0, 1.0) * vein
        },
        9,
    ));
    v.push(make(
        "Flat Marker",
        TIP_PX,
        TIP_PX,
        |x, y, _| {
            let inside = x.abs() < 0.92 && y.abs() < 0.32;
            if inside {
                1.0 - 0.15 * fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 30, 91)
            } else {
                0.0
            }
        },
        10,
    ));
    v
}

/// Procedural grain textures shipped with the app (tileable).
pub fn builtin_textures() -> Vec<TipImage> {
    let mut v = Vec::new();
    v.push(make("Fine Grain", TEX_PX, TEX_PX, |_, _, r| 0.55 + r.signed() * 0.45, 100));
    v.push(make("Coarse Noise", TEX_PX, TEX_PX, |x, y, _| fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 16, 101) * 1.4 - 0.2, 101));
    v.push(make(
        "Rough Paper",
        TEX_PX,
        TEX_PX,
        |x, y, r| {
            let n = fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 8, 102);
            0.35 + n * 0.55 + r.signed() * 0.12
        },
        102,
    ));
    v.push(make(
        "Canvas",
        TEX_PX,
        TEX_PX,
        |x, y, r| {
            let u = (x * 0.5 + 0.5) * TEX_PX as f32;
            let v = (y * 0.5 + 0.5) * TEX_PX as f32;
            let wx = ((u / 4.0) * std::f32::consts::PI).sin().abs();
            let wy = ((v / 4.0) * std::f32::consts::PI).sin().abs();
            0.35 + 0.35 * wx.max(wy) + 0.2 * wx.min(wy) + r.signed() * 0.08
        },
        103,
    ));
    v.push(make(
        "Dots",
        TEX_PX,
        TEX_PX,
        |x, y, _| {
            let u = ((x * 0.5 + 0.5) * 8.0).fract() - 0.5;
            let v = ((y * 0.5 + 0.5) * 8.0).fract() - 0.5;
            let d = (u * u + v * v).sqrt();
            ((0.3 - d) / 0.06).clamp(0.0, 1.0)
        },
        104,
    ));
    v.push(make(
        "Diagonal Lines",
        TEX_PX,
        TEX_PX,
        |x, y, _| {
            let t = ((x + y) * 0.5 * 12.0).fract();
            ((0.5 - (t - 0.5).abs()) / 0.2).clamp(0.0, 1.0)
        },
        105,
    ));
    v.push(make(
        "Crosshatch",
        TEX_PX,
        TEX_PX,
        |x, y, _| {
            let a = ((x + y) * 0.5 * 10.0).fract();
            let b = ((x - y) * 0.5 * 10.0).fract();
            let la = ((0.5 - (a - 0.5).abs()) / 0.18).clamp(0.0, 1.0);
            let lb = ((0.5 - (b - 0.5).abs()) / 0.18).clamp(0.0, 1.0);
            la.max(lb)
        },
        106,
    ));
    v.push(make(
        "Concrete",
        TEX_PX,
        TEX_PX,
        |x, y, r| {
            let n = fbm(x * 0.5 + 0.5, y * 0.5 + 0.5, 6, 107);
            let pits = if r.unit() < 0.05 { 0.0 } else { 1.0 };
            (0.5 + (n - 0.5) * 1.2) * pits
        },
        107,
    ));
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtins_are_well_formed() {
        for t in builtin_tips().into_iter().chain(builtin_textures()) {
            assert_eq!(t.alpha.len(), (t.width * t.height) as usize, "{}", t.name);
            assert!(t.alpha.iter().all(|a| (0.0..=1.0).contains(a)), "{}", t.name);
            assert!(t.alpha.iter().any(|a| *a > 0.1), "{} is empty", t.name);
            assert!(t.builtin);
        }
    }

    #[test]
    fn tip_sampling_wraps_and_clips() {
        let t = TipImage::from_alpha("t", 2, 2, vec![1.0, 0.0, 0.0, 1.0]);
        assert_eq!(t.texel(-1, 0), 0.0);
        assert_eq!(t.texel(2, 2), 1.0);
        assert_eq!(t.sample_tip(2.0, 0.0), 0.0);
        assert!(t.sample_tip(-0.5, -0.5) > 0.9);
    }

    #[test]
    fn dark_pixels_make_strong_tips() {
        let t = TipImage::from_rgba_dark("t", 2, 1, &[0, 0, 0, 255, 255, 255, 255, 255]);
        assert!(t.alpha[0] > 0.99 && t.alpha[1] < 0.01);
    }
}
